# Generated by Django 3.2.6 on 2021-08-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appX', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
